name: Rate Card Pro CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  api-test:
    name: Backend API Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Initialize database
        run: |
          source .venv/bin/activate
          python -c "from database import init_db; init_db()"
      
      - name: Run server and health check
        run: |
          source .venv/bin/activate
          uvicorn main:app --host 127.0.0.1 --port 8080 &
          sleep 5
          curl -f http://127.0.0.1:8080/healthz || exit 1
      
      - name: Seed test data
        run: |
          curl -X POST http://127.0.0.1:8080/seed_admin
  
  frontend-typecheck:
    name: Frontend Type Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npx tsc --noEmit
      
      - name: Lint
        run: npx eslint . --ext .ts,.tsx || true
  
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [api-test, frontend-typecheck]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      
      - name: Install frontend dependencies
        run: npm ci
      
      - name: Start backend
        working-directory: backend
        run: |
          source .venv/bin/activate
          python -c "from database import init_db; init_db()"
          uvicorn main:app --host 127.0.0.1 --port 8080 &
          sleep 5
      
      - name: Seed data and test workflow
        run: |
          # Seed admin users
          curl -X POST http://127.0.0.1:8080/seed_admin
          
          # Login as AM
          AM_TOKEN=$(curl -s -X POST "http://127.0.0.1:8080/auth/login" \
            -H "Content-Type: application/json" \
            -d '{"email":"am@example.com","password":"am123"}' | jq -r '.token')
          
          echo "AM Token: $AM_TOKEN"
          
          # Create request
          REQUEST_ID=$(curl -s -X POST "http://127.0.0.1:8080/requests" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $AM_TOKEN" \
            -d '{
              "name": "Test Quote",
              "items": [
                {"description": "Senior Developer", "qty": 40, "rate": 6500}
              ]
            }' | jq -r '.id')
          
          echo "Created Request ID: $REQUEST_ID"
          
          # Submit request
          curl -s -X POST "http://127.0.0.1:8080/requests/$REQUEST_ID/submit" \
            -H "Authorization: Bearer $AM_TOKEN"
          
          # Login as FD
          FD_TOKEN=$(curl -s -X POST "http://127.0.0.1:8080/auth/login" \
            -H "Content-Type: application/json" \
            -d '{"email":"fd@example.com","password":"admin123"}' | jq -r '.token')
          
          echo "FD Token: $FD_TOKEN"
          
          # Approve request
          curl -s -X POST "http://127.0.0.1:8080/approvals/$REQUEST_ID/approve" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $FD_TOKEN" \
            -d '{"note": "CI Test Approval"}'
          
          # Check PDF generation
          PDF_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:8080/pdf/$REQUEST_ID")
          
          if [ "$PDF_STATUS" -eq 200 ]; then
            echo "✅ PDF generation successful"
          else
            echo "❌ PDF generation failed with status $PDF_STATUS"
            exit 1
          fi
          
          echo "✅ Integration test completed successfully"
