// MCP Marketplace Mock Data
import { MCPProvider, MCPProduct } from './types';

export const FEATURED_PROVIDERS: MCPProvider[] = [
  {
    id: 'factset',
    name: 'FactSet',
    slug: 'factset',
    description: 'Financial data and software solutions for investment professionals',
    logoInitials: 'FS',
    website: 'https://www.factset.com',
    categories: ['financial', 'analytics'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'komodo-health',
    name: 'Komodo Health',
    slug: 'komodo-health',
    description: 'Healthcare intelligence platform connecting patient insights',
    logoInitials: 'KH',
    website: 'https://www.komodohealth.com',
    categories: ['health', 'analytics'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'magnite',
    name: 'Magnite',
    slug: 'magnite',
    description: 'Sell-side advertising platform for publishers',
    logoInitials: 'MG',
    website: 'https://www.magnite.com',
    categories: ['media', 'analytics'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'moodys',
    name: "Moody's",
    slug: 'moodys',
    description: 'Global credit ratings, research, and risk analysis',
    logoInitials: 'MD',
    website: 'https://www.moodys.com',
    categories: ['financial', 'data-enrichment'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'sp-global',
    name: 'S&P Global Market Intelligence',
    slug: 'sp-global',
    description: 'Essential intelligence for capital and commodity markets',
    logoInitials: 'SP',
    website: 'https://www.spglobal.com',
    categories: ['financial', 'analytics', 'data-enrichment'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'glean',
    name: 'Glean',
    slug: 'glean',
    description: 'Enterprise AI search and knowledge management',
    logoInitials: 'GL',
    website: 'https://www.glean.com',
    categories: ['productivity', 'ai-models'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'dun-bradstreet',
    name: 'Dun & Bradstreet',
    slug: 'dun-bradstreet',
    description: 'Business data and analytics for risk management',
    logoInitials: 'DB',
    website: 'https://www.dnb.com',
    categories: ['financial', 'data-enrichment'],
    isFeatured: true,
    isPartnerConnect: true,
    isVerified: true,
  },
  {
    id: 'bright-data',
    name: 'Bright Data',
    slug: 'bright-data',
    description: 'Web data collection and proxy infrastructure',
    logoInitials: 'BD',
    website: 'https://www.brightdata.com',
    categories: ['data-enrichment', 'analytics'],
    isFeatured: true,
    isPartnerConnect: false,
    isVerified: true,
  },
];

export const MCP_PRODUCTS: MCPProduct[] = [
  // Financial Data Products
  {
    id: 'factset-fundamentals',
    providerId: 'factset',
    providerName: 'FactSet',
    name: 'FactSet Fundamentals',
    slug: 'factset-fundamentals',
    description: 'Access comprehensive company fundamentals, financials, and estimates data via MCP',
    categories: ['financial', 'analytics'],
    tags: ['fundamentals', 'financials', 'equities', 'research'],
    pricing: { type: 'contact-sales' },
    capabilities: [
      { id: 'get-financials', name: 'Get Financials', description: 'Retrieve income statements, balance sheets, cash flows', type: 'tool' },
      { id: 'get-estimates', name: 'Get Estimates', description: 'Access analyst estimates and consensus data', type: 'tool' },
      { id: 'company-profile', name: 'Company Profile', description: 'Get detailed company information and classifications', type: 'resource' },
    ],
    isFree: false,
    isInstantlyAvailable: false,
    isNew: false,
    rating: 4.8,
    reviewCount: 127,
    installCount: 2340,
    createdAt: '2024-06-15',
    updatedAt: '2025-11-20',
  },
  {
    id: 'moodys-credit-ratings',
    providerId: 'moodys',
    providerName: "Moody's",
    name: "Moody's Credit Ratings API",
    slug: 'moodys-credit-ratings',
    description: "Access Moody's credit ratings and research through natural language queries",
    categories: ['financial', 'data-enrichment'],
    tags: ['credit', 'ratings', 'risk', 'bonds'],
    pricing: { type: 'contact-sales' },
    capabilities: [
      { id: 'get-rating', name: 'Get Credit Rating', description: 'Retrieve credit ratings for entities and instruments', type: 'tool' },
      { id: 'rating-history', name: 'Rating History', description: 'Access historical rating changes and outlooks', type: 'tool' },
      { id: 'credit-research', name: 'Credit Research', description: 'Search and retrieve credit research reports', type: 'resource' },
    ],
    isFree: false,
    isInstantlyAvailable: false,
    isNew: true,
    rating: 4.9,
    reviewCount: 89,
    installCount: 1567,
    createdAt: '2025-08-10',
    updatedAt: '2025-12-01',
  },
  {
    id: 'sp-market-data',
    providerId: 'sp-global',
    providerName: 'S&P Global',
    name: 'S&P Market Intelligence',
    slug: 'sp-market-data',
    description: 'Real-time and historical market data from S&P Global via MCP tools',
    categories: ['financial', 'analytics'],
    tags: ['market-data', 'indices', 'pricing', 'commodities'],
    pricing: { type: 'paid', startingPrice: 999, currency: 'USD', billingPeriod: 'monthly' },
    capabilities: [
      { id: 'get-prices', name: 'Get Prices', description: 'Real-time and historical security prices', type: 'tool' },
      { id: 'get-indices', name: 'Get Index Data', description: 'S&P index constituents and performance', type: 'tool' },
      { id: 'market-screener', name: 'Market Screener', description: 'Screen securities by custom criteria', type: 'tool' },
    ],
    isFree: false,
    isInstantlyAvailable: true,
    isNew: false,
    rating: 4.7,
    reviewCount: 234,
    installCount: 4521,
    createdAt: '2024-03-20',
    updatedAt: '2025-10-15',
  },
  // Productivity Products
  {
    id: 'glean-search',
    providerId: 'glean',
    providerName: 'Glean',
    name: 'Glean Enterprise Search',
    slug: 'glean-search',
    description: 'AI-powered enterprise search across all your connected applications',
    categories: ['productivity', 'ai-models'],
    tags: ['search', 'knowledge', 'enterprise', 'ai'],
    pricing: { type: 'freemium' },
    capabilities: [
      { id: 'search', name: 'Enterprise Search', description: 'Search across all connected data sources', type: 'tool' },
      { id: 'ask', name: 'Ask Glean', description: 'Natural language Q&A over your enterprise data', type: 'tool' },
      { id: 'summarize', name: 'Summarize', description: 'Generate summaries of documents and conversations', type: 'tool' },
    ],
    isFree: false,
    isInstantlyAvailable: true,
    isNew: false,
    rating: 4.6,
    reviewCount: 456,
    installCount: 8901,
    createdAt: '2024-01-10',
    updatedAt: '2025-11-28',
  },
  // Data Enrichment Products
  {
    id: 'dnb-company-data',
    providerId: 'dun-bradstreet',
    providerName: 'Dun & Bradstreet',
    name: 'D&B Company Data',
    slug: 'dnb-company-data',
    description: 'Enrich your data with comprehensive company information from D&B',
    categories: ['financial', 'data-enrichment'],
    tags: ['company-data', 'enrichment', 'firmographics', 'duns'],
    pricing: { type: 'paid', startingPrice: 500, currency: 'USD', billingPeriod: 'monthly' },
    capabilities: [
      { id: 'company-lookup', name: 'Company Lookup', description: 'Look up company by DUNS number or name', type: 'tool' },
      { id: 'hierarchy', name: 'Corporate Hierarchy', description: 'Get corporate family tree and relationships', type: 'tool' },
      { id: 'risk-score', name: 'Risk Assessment', description: 'Get D&B risk scores and payment predictors', type: 'tool' },
    ],
    isFree: false,
    isInstantlyAvailable: true,
    isNew: false,
    rating: 4.5,
    reviewCount: 312,
    installCount: 3456,
    createdAt: '2024-04-05',
    updatedAt: '2025-09-20',
  },
  {
    id: 'bright-data-web',
    providerId: 'bright-data',
    providerName: 'Bright Data',
    name: 'Bright Data Web Collector',
    slug: 'bright-data-web',
    description: 'Collect structured data from any website with AI-powered extraction',
    categories: ['data-enrichment', 'analytics'],
    tags: ['web-scraping', 'data-collection', 'automation'],
    pricing: { type: 'freemium' },
    capabilities: [
      { id: 'scrape-url', name: 'Scrape URL', description: 'Extract structured data from any web page', type: 'tool' },
      { id: 'search-serp', name: 'SERP Search', description: 'Get search engine results programmatically', type: 'tool' },
      { id: 'ecommerce', name: 'E-commerce Data', description: 'Collect product, pricing, and review data', type: 'tool' },
    ],
    isFree: false,
    isInstantlyAvailable: true,
    isNew: true,
    rating: 4.4,
    reviewCount: 178,
    installCount: 2890,
    createdAt: '2025-06-01',
    updatedAt: '2025-12-05',
  },
  // Health Products
  {
    id: 'komodo-patient-insights',
    providerId: 'komodo-health',
    providerName: 'Komodo Health',
    name: 'Komodo Patient Insights',
    slug: 'komodo-patient-insights',
    description: 'HIPAA-compliant patient journey analytics and healthcare intelligence',
    categories: ['health', 'analytics'],
    tags: ['healthcare', 'patient-journey', 'clinical', 'pharma'],
    pricing: { type: 'contact-sales' },
    capabilities: [
      { id: 'patient-journey', name: 'Patient Journey', description: 'Analyze de-identified patient treatment pathways', type: 'tool' },
      { id: 'provider-search', name: 'Provider Search', description: 'Find healthcare providers by specialty and location', type: 'tool' },
      { id: 'market-analytics', name: 'Market Analytics', description: 'Healthcare market size and share analysis', type: 'resource' },
    ],
    isFree: false,
    isInstantlyAvailable: false,
    isNew: false,
    rating: 4.7,
    reviewCount: 67,
    installCount: 890,
    createdAt: '2024-09-15',
    updatedAt: '2025-11-10',
  },
  // Media Products
  {
    id: 'magnite-ad-analytics',
    providerId: 'magnite',
    providerName: 'Magnite',
    name: 'Magnite Ad Analytics',
    slug: 'magnite-ad-analytics',
    description: 'Programmatic advertising analytics and inventory insights',
    categories: ['media', 'analytics'],
    tags: ['advertising', 'programmatic', 'inventory', 'yield'],
    pricing: { type: 'paid', startingPrice: 750, currency: 'USD', billingPeriod: 'monthly' },
    capabilities: [
      { id: 'inventory-analysis', name: 'Inventory Analysis', description: 'Analyze ad inventory performance and fill rates', type: 'tool' },
      { id: 'demand-insights', name: 'Demand Insights', description: 'Understand buyer demand and bidding patterns', type: 'tool' },
      { id: 'yield-optimization', name: 'Yield Optimization', description: 'Get recommendations for revenue optimization', type: 'prompt' },
    ],
    isFree: false,
    isInstantlyAvailable: true,
    isNew: false,
    rating: 4.3,
    reviewCount: 89,
    installCount: 1234,
    createdAt: '2024-07-20',
    updatedAt: '2025-10-30',
  },
  // Free Products
  {
    id: 'expense-classifier-ai',
    providerId: 'internal',
    providerName: 'IPAI Scout',
    name: 'Expense Classifier AI',
    slug: 'expense-classifier-ai',
    description: 'Automatically classify and categorize expenses using AI with BIR tax category mapping',
    categories: ['financial', 'productivity'],
    tags: ['expense', 'classification', 'tax', 'automation', 'philippines'],
    pricing: { type: 'free' },
    capabilities: [
      { id: 'classify-expense', name: 'Classify Expense', description: 'Categorize expenses into standard categories', type: 'tool' },
      { id: 'extract-receipt', name: 'Extract Receipt', description: 'OCR and extract data from receipt images', type: 'tool' },
      { id: 'bir-mapping', name: 'BIR Tax Mapping', description: 'Map expenses to BIR tax deduction categories', type: 'tool' },
    ],
    isFree: true,
    isInstantlyAvailable: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 45,
    installCount: 567,
    createdAt: '2025-11-01',
    updatedAt: '2025-12-07',
  },
  {
    id: 'ppm-task-creator',
    providerId: 'internal',
    providerName: 'IPAI Scout',
    name: 'PPM BIR Task Creator',
    slug: 'ppm-task-creator',
    description: 'Automatically create and manage BIR compliance tasks in your PPM system',
    categories: ['financial', 'productivity'],
    tags: ['ppm', 'compliance', 'bir', 'tax', 'automation'],
    pricing: { type: 'free' },
    capabilities: [
      { id: 'create-bir-tasks', name: 'Create BIR Tasks', description: 'Generate 3-step task workflow for each BIR form', type: 'tool' },
      { id: 'deadline-alerts', name: 'Deadline Alerts', description: 'Get notifications for upcoming BIR deadlines', type: 'tool' },
      { id: 'compliance-status', name: 'Compliance Status', description: 'Check BIR compliance status for current period', type: 'resource' },
    ],
    isFree: true,
    isInstantlyAvailable: true,
    isNew: true,
    rating: 4.6,
    reviewCount: 23,
    installCount: 234,
    createdAt: '2025-11-15',
    updatedAt: '2025-12-07',
  },
];

export const FILTER_TABS = [
  { id: 'popular', label: 'Popular' },
  { id: 'free', label: 'Free and instantly available' },
  { id: 'new', label: 'New or recently updated' },
  { id: 'financial', label: 'Financial' },
  { id: 'media', label: 'Media' },
  { id: 'health', label: 'Health and life sciences' },
  { id: 'retail', label: 'Retail' },
  { id: 'transportation', label: 'Transportation and Logistics' },
  { id: 'from-ipai', label: 'From IPAI Scout' },
] as const;
